logging:
  level:
    root: WARN
    hm.binkley.labs.Application: INFO

spring:
  application:
    name: Bob
  output:
    ansi:
      enabled: always  # Lie because Spring does not grok Cygwin

---

spring:
  profiles: test

logging:
  level:
    hm.binkley.labs.Application: WARN
